version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL= #zostało zmienone
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: #zostało zmienone
      POSTGRES_DB: #zostało zmienone
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
